### ISSUE TITLE
Random queue name "amq.gen-X678K5...."

### ISSUE THREAD

**Issue by nelsou** [Stratio/Spark-RabbitMQ#15]
Hello,

I'm using the current trunk and I'm having a strange behaviour.

When I run Spark Streaming with the RabbitMQ receiver, it creates a random queuename "amq.gen-X678K5...." and read from it. It doesn't read the one I specified in the queueName ...

Any idea ?

**Comment by nelsou** [comment]
BTW, In my code, I merged the 2 pull requests (fixed vHost and thread), you should do it too :)

**Comment by nelsou** [comment]
ok got it !
If you specify "routingKeys", it will create the binding between the exchange and a random queue.
If you do not specify "routingKeys", it will create a queue based on the queueName value

But I want to use an existing queue :)

**Comment by danielcsant** [comment]
You're rigth nelsou. That's a known bug that we have to fix

We'll merge them as soon as possible

Thanks!

**Comment by Gschiavon** [comment]
Hi nelsou,

There is a pull request that solve this issue.

Thanks a lot.
