### ISSUE TITLE
Maven Repository is outdated

### ISSUE THREAD

**Issue by KevinMellott91** [Stratio/Spark-RabbitMQ#17]
Is there a date for the next planned release of this component? It would be nice to have a new version uploaded to the [Maven repository](http://search.maven.org/#search%7Cga%7C1%7Ccom.stratio.receiver) for reference in a consumer's pom.xml file.

If you'd like me to create a new version as a pull request, I'd be happy to do so (just let me know).

Thanks!

**Comment by danielcsant** [comment]
You are right, we need to upload a new version to Maven repository.

There are some issues like #5, #11 and #15 that we want to fix before upload the new version.

Thanks for your interest

**Comment by pawelantczak** [comment]
Hello.
Is this lib still supported? 
Regards.

**Comment by danielcsant** [comment]
Hello,

We have just release a new version:

[spark-rabbitmq_1.4 0.2.0](http://search.maven.org/#artifactdetails%7Ccom.stratio.receiver%7Cspark-rabbitmq_1.4%7C0.2.0%7Cjar)
[spark-rabbitmq_1.5 0.2.0](http://search.maven.org/#artifactdetails%7Ccom.stratio.receiver%7Cspark-rabbitmq_1.5%7C0.2.0%7Cjar)

Regards
