### ISSUE TITLE
Steaming exceptions cause data loss

### ISSUE THREAD

**Issue by geott6758** [Stratio/Spark-RabbitMQ#28]
there is a problem that how to ensure that the data is not lost When the streaming is wrong

**Comment by aafri** [comment]
The details is follow this:
When RabbitMQInputDStream is receive the rabbitMQ data, then ack to delete the source data in MQ.
But unfortunately, the executor crash for some reason , the data in streaming is not process finished,and the result .
This make data lost:
1、 the data in MQ is delete,
2、the data in streaming is not process finished and did not store .
So RabbitMQUtils is  not reliable.

Forgive my poor English.
Best Regards!

**Comment by frascuchon** [comment]
Hi,

It would be nice set rabbitmq client ack mode by configuration and send a ack after store the delivered message 

Best Regards!

**Comment by aafri** [comment]
Yes,we store the data in HBase now befor ack ,and delete after the data is process .

**Comment by compae** [comment]
Hi,

this issue is solved in the PR #41.
The user can configure the Ack policy with the DStream params.

Thanks for all.
