### ISSUE TITLE
Queue is created without binding to exchange.

### ISSUE THREAD

**Issue by we7313** [Stratio/Spark-RabbitMQ#29]
I have an issue where the queue gets created but the queue never gets bound to the exchange.
If I manually login to RabbitMQ's web portal I can add the queue to the correct exchange & everything works perfectly.  I was hoping this would get re-established automatically when starting the spark job.

I've debugged the app and it appears to be passing in the correct key value ('exchangeName', 'MyExchange')
Any ideas why this is occurring?
-Will

**Comment by aafri** [comment]
RabbitMQ have many type of Queue ,U should set the  correct parameter when you read from Queue.I think this not  a issue of Spark-RabbitMQ .

**Comment by we7313** [comment]
I have set the following parameters:
"host" 
"queueName" 
"exchangeName"
"exchangeType"
"vHost"
"username" 
"password"
I there a parameter that must be set that I am missing?

**Comment by Gschiavon** [comment]
Hi we7313,

First of all, we would need an error trace if there is one to try to fix it or understand what's going on. 

By the way, do you need all these parameters? Username, password , etc?

Regards.

**Comment by we7313** [comment]
There is no error, the queue is created successfully.  It is just not bound to an exchange.
If I manually bind it to the desired exchange in the rabbitmq web interface it works fine.

Yes, I need login credentials.
Its as if it is not using the exchange variable at all.

**Comment by Gschiavon** [comment]
Hi,
are you using the last version? We fixed several bugs about binding queues.

If you are already using the latest version, tell me step by step what you are trying and we will check it.

Regards.

**Comment by KevinMellott91** [comment]
I believe that the issue occurs when you specify a queue and an exchange, but do not specify any routing keys. If you trace this scenario to the `getQueueName` method, it appears that RabbitMQ's `channel.queueBind` is never called. Therefore, the queue is never bound to the exchange (unless you are using a specific routing key).

I've been playing around with this workflow and believe that I have found a fix. Tomorrow I'll clean up my code a little and submit a PR for you to examine.

**Comment by KevinMellott91** [comment]
I just submitted PR #31 to address this issue.

**Comment by KevinMellott91** [comment]
PR has been merged (thanks!) - this issue can be closed.
