### ISSUE TITLE
Only Strings are supported

### ISSUE THREAD

**Issue by mwacc** [Stratio/Spark-RabbitMQ#4]
Current;y, only String events are supported due to 
store(new String(delivery.getBody))  // in RabbitMQInputDStream.scala
it's better to provide generic ByteArray wrapper to give end user a chance to identify object type. 
Because of, non string objects can't be transferred now

**Comment by dmorales-stratio** [comment]
Thanks, we will update the receiver asap.

**Comment by koen-dejonghe** [comment]
Here's a link to a gist with a possible implementation:
https://gist.github.com/koen-dejonghe/940e0d5f3fc6c2b2d39c
It uses a separate message consumer (extension of DefaultConsumer), which may be possible way of solving.

**Comment by danielcsant** [comment]
Thank you very much Koen. We will take a look to your code

**Comment by spacely** [comment]
Hello, has a byteArray reader for RabbitMQ for Spark been added to the code base yet by any chance? Thanks.

**Comment by compae** [comment]
Hi,

this issue is solved in the PR #41 with generic type, additionally are been implemented the DStream creation with String and Array[Byte] types.

Thanks for all.
