### ISSUE TITLE
Direct Aproach

### ISSUE THREAD

**Issue by JoaquinSV** [Stratio/Spark-RabbitMQ#40]
Hi, are you thinking to add a Direct aproach like Kafka plugin? it could be very useful.
http://spark.apache.org/docs/latest/streaming-kafka-integration.html#approach-2-direct-approach-no-receivers

**Comment by danielcsant** [comment]
Hi,
We have thought about it and it will improve the performance a lot but we are not going to implement it in the short-term .

**Comment by compae** [comment]
Hi Joaquin,

we are implemented this feature in the PR #41, if you want you can review the code or if you have any question, I can help you.

In the next days we update the overview and in Stratio we publish one post in our blog with all the new functionalities explained.

Thanks for all.
