### ISSUE TITLE
How to read messages from RabbitMQ from multiple queues

### ISSUE THREAD

**Issue by tsatya** [Stratio/spark-rabbitmq#46]
Hi,
I have a requirement where I have to read from multiple rabbitmq queues. Can anyone help me with some java code. I am able to read with a single queue.

**Comment by compae** [comment]
Hi,

The last week I have been implementing a new approach to consume messages from multiple queues. 

The Pull Request is #41. Is possible that we merge it today. 

Thanks for all.

**Comment by tsatya** [comment]
Hi,
Can you please piece of code how it will be implemented in java.
Please share the entire code, dependency and other details.

**Comment by tsatya** [comment]
Looks like still it has not been merged to the master branch ?

**Comment by compae** [comment]
Hi,

The last friday we merged in master the PR.

You can use the function : 

def createJavaDistributedStream[R]

In the distributedTest you can see how you can use the new functionality.

Thanks.

**Comment by tsatya** [comment]
ok...It will be great if you can share me the java code. It will be very helpful since I am very new to spark.

**Comment by compae** [comment]
Hi @tsatya, in the last two PR you can find examples to use the java implementation:

[Receiver approach in java](https://github.com/Stratio/Spark-RabbitMQ/blob/master/src/test/java/org/apache/spark/streaming/rabbitmq/JavaRabbitMQConsumer.java)

[Distributed approach in java](https://github.com/Stratio/Spark-RabbitMQ/blob/master/src/test/java/org/apache/spark/streaming/rabbitmq/JavaRabbitMQDistributedConsumer.java)
