### ISSUE TITLE
Where to find a full Scala or Java code example like for the previous version ?

### ISSUE THREAD

**Issue by enahwe** [Stratio/spark-rabbitmq#47]
Hi,
- As a simple user I am, the following Java code example line as described from your current README isn't enough :

JavaReceiverInputDStream receiverStream = RabbitMQUtils.createJavaDistributedStream[R]](javaSparkStreamingContext, params, JFunction[Array[Byte], R]);

Can you tell where is it possible to find a deeper example ?

Kind Regards,

**Comment by compae** [comment]
Hi @enahwe , in the last two PR you can find examples to use the java implementation:

[Receiver approach in java](https://github.com/Stratio/Spark-RabbitMQ/blob/master/src/test/java/org/apache/spark/streaming/rabbitmq/JavaRabbitMQConsumer.java)

[Distributed approach in java](https://github.com/Stratio/Spark-RabbitMQ/blob/master/src/test/java/org/apache/spark/streaming/rabbitmq/JavaRabbitMQDistributedConsumer.java)
