### ISSUE TITLE
Unsupported Spark 1.4.1

### ISSUE THREAD

**Issue by nelsou** [Stratio/Spark-RabbitMQ#5]
Current version of RabbitMQ receiver doesn't support Spark 1.4.1

Is is hard to fix ?

**Comment by danielcsant** [comment]
It seems it is not hard but we have to study it. The idea is to have two branches and keep the compatibility with the last two versions of Spark. We will working on this in the following days

**Comment by nelsou** [comment]
Awesome Daniel, I will follow your commits.

**Comment by Gschiavon** [comment]
Hi Nelosu,
Pull request #25 support different Spark versions.
Regards.

**Comment by danielcsant** [comment]
Closing this issue. 
Version Spark-RabbitMQ 0.2.0 supports Spark versions 1.4.1 and 1.5.2
