### ISSUE TITLE
Receive message properties

### ISSUE THREAD

**Issue by jrglee** [Stratio/spark-rabbitmq#51]
This receiver only consumes the body portion of the message but we often need to read some extra metadata from a RabbitMQ message like the headers or the routing key. It would be great if we could get a DStream of a `RabbitMQMessage` with message properties and headers.

I can submit a PR if you want.

**Comment by compae** [comment]
Hi @jrglee,

You can make one PR and then we can review the code and the feature.

Thanks for all.

**Comment by fpousserot** [comment]
Hi @jrglee, As you,  I need to read the properties metadata. Can you share your version / PR ?

**Comment by pedroszattoni** [comment]
Hello @jrglee and @fpousserot, just like you guys, I need the metadata from the RabbitMQ messages as well. Could any of you share your version? I would highly appreciate it.

**Comment by stephaneseng** [comment]
Hi @pedroszattoni @fpousserot @jrglee and @compae, just to let you know, I have submitted a PR (#77) for this issue.

**Comment by jrglee** [comment]
Sorry for not being able to submit a PR. We ended switching from RabbitMQ to Kafka a few months ago.

**Comment by pedroszattoni** [comment]
Hello @stephaneseng. A while ago,  manege to modify the receiver, so that it returns tuples of messages body and routing keys, which was what I needed. Even so, I appreciate your contribution. Thank you.

**Comment by compae** [comment]
Hi @pedroszattoni @fpousserot  @jrglee and @stephaneseng the PR have been merged now, thanks all for the job, in special to @stephaneseng
