### ISSUE TITLE
Multiple queue priority

### ISSUE THREAD

**Issue by axle-h** [Stratio/spark-rabbitmq#58]
Is there a way of consuming from multiple queues with a distributed stream according to a priority order e.g.

Two queues: primary and secondary. We prefer to consume primary but will take messages from secondary when there's spare capacity.

To implement we could check the number of messages consumed from the primary queue against a fraction of maxMessagesPerPartition on a corresponding time fraction of the stream batch size. With a stream batch size of 10 seconds and maxMessagesPerPartition  = 1000, we would check the stream for priority every second, expecting to see 100 messages. We could limit each stream fraction to 100 messages and compare actual consumption against expected. Where we have spare capacity in any stream fraction (consumed from primary), we could consume from the secondary queue on the next.

Is this possible? Happy to write it if you'd accept as a PR.

**Comment by compae** [comment]
I think that it could be interesting, is possible to implement this with adding options in RabbitMQPartition and inside the classes RabbitMQRDD and RabbitMQDStream. 

If you want, you can work in this feature and then open one PR, we can discuss the implementation inside the PR. 

Thanks for all @axle-h
