### ISSUE TITLE
Issue with vHost vs virtualHost

### ISSUE THREAD

**Issue by nelsou** [Stratio/Spark-RabbitMQ#59]
Documentation says:
virtualHosts: RabbitMQ virtual Host
vHost: RabbitMQ vHost

Are they the same ? Cause I lost 1 hour using vHost instead of virtualHost :)

**Comment by compae** [comment]
Sorry, I change the documentation... the correct key is virtualHosts, in this file you have all the parameters:

[ConfigParameters.scala](https://github.com/Stratio/Spark-RabbitMQ/blob/master/src/main/scala/org/apache/spark/streaming/rabbitmq/ConfigParameters.scala)

**Comment by nelsou** [comment]
thx @compae

**Comment by armaseg** [comment]
Hello, 

Is it normal that on the documentations are both keys still on it ?

Also, on **RabbitMQDistributedConsumerIT.scala** on c2f818984a31ecf622f4c98ce5e72cde9b6f8e88 , vHost key used is rather than virtualHosts.

Regards,
