### ISSUE TITLE
spark streaming checkpoint

### ISSUE THREAD

**Issue by louishigher** [Stratio/spark-rabbitmq#60]
Do I have to do checkpoint with `RabbitMQUtils.createDistributedStream`? If so,How can I do it? Is `RabbitMQUtils.createDistributedStream` only put in MAIN method?

**Comment by compae** [comment]
You need to create correcly the SparkStreaming Context. 

In the spark documentation you have one example: 

```scala
// Function to create and setup a new StreamingContext
def functionToCreateContext(): StreamingContext = {
    val ssc = new StreamingContext(...)   // new context
    val lines = ssc.socketTextStream(...) // create DStreams
    ...
    ssc.checkpoint(checkpointDirectory)   // set checkpoint directory
    ssc
}

// Get StreamingContext from checkpoint data or create a new one
val context = StreamingContext.getOrCreate(checkpointDirectory, functionToCreateContext _)

// Do additional setup on context that needs to be done,
// irrespective of whether it is being started or restarted
context. ...

// Start the context
context.start()
context.awaitTermination()
```

**Comment by louishigher** [comment]
Thank you for replying！In this way ，do I have to set the **AckType** to basic or enable the WAL？

**Comment by compae** [comment]
Hi @louishigher 

Using this design pattern in SparkStreaming context creation, you have HA in the RDDs received, but in production environments you need to activate the ACK in rabbitMQReceiver.

Thanks for all.
