### ISSUE TITLE
Spark-RabbitMQ V4 is not loaded in maven repository. 

### ISSUE THREAD

**Issue by fpousserot** [Stratio/spark-rabbitmq#61]
Hi,
Spark-RabbitMQ V4 is not loaded in maven repository. 

What are the operations required to use version 4 ?

I add the next dependency in my pom.xml:

```
<dependency>
  <groupId>com.stratio.receiver</groupId>
  <artifactId>spark-rabbitmq</artifactId>
  <version>LATEST</version>
</dependency>
```

I tried a gitclone , a build that added the jar in my local repository. In my java project maven tells me it is not com.stration so I tried achieve a `mvn install : install -file` . The `mvn clean install`seems to understand the operation but the declaration of `import eclispe com.stratio.receiver.RabbitMQUtils` does not work: "do not resolved "

Merci !

**Comment by fpousserot** [comment]
if i declare ` import org.apache.spark.streaming.rabbitmq.RabbitMQUtils` , the build work. But i don't know if my operations for import v4 of spark-rabbitmq it's good :(

**Comment by compae** [comment]
The package was changed in previous PR  to  ` import org.apache.spark.streaming.rabbitmq.RabbitMQUtils` 

the maven dependency is 

```
<dependency>
    <groupId>com.stratio.receiver</groupId>
    <artifactId>spark-rabbitmq_1.6</artifactId>
    <version>0.3.0</version>
</dependency>
```
