### ISSUE TITLE
Add support for spark 2 module

### ISSUE THREAD

**Issue by eranmiz132** [Stratio/spark-rabbitmq#65]

**Comment by compae** [comment]
Could you provide one description to this issue.

**Comment by eranmiz132** [comment]
Spark 2 was just released, and the library lack support for this version

**Comment by palaiyacw** [comment]
What's the status of this issue?

**Comment by compae** [comment]
The next weeks we develop the compatibility with last release of Spark.

Thanks for yours comments

**Comment by pedroszattoni** [comment]
Hello @compae,
Is there any expected date to the release of version compatible with Spark 2.0.0?
Thank you.

**Comment by compae** [comment]
The PR #90 support Spark 2.0 in the version 0.5 will be available.

Thanks for all.

**Comment by compae** [comment]
Can I close this issue @eranmiz132 @palaiyacw @pedroszattoni ??

**Comment by pedroszattoni** [comment]
Yes. Thank you, @compae !

**Comment by palaiyacw** [comment]
@compae Thanking You :+1:
