### ISSUE TITLE
Deploy artifacts to a repository

### ISSUE THREAD

**Issue by eranmiz132** [Stratio/spark-rabbitmq#66]
Like
mvnrepository.com

**Comment by compae** [comment]
You have available this artifacts in spark packages and in [maven central](http://search.maven.org/#artifactdetails%7Ccom.stratio.receiver%7Cspark-rabbitmq_1.6%7C0.3.0%7Cjar)

**Comment by nelsou** [comment]
When do you plan to republish it ? (I saw a fix regarding "connection already closed")

**Comment by compae** [comment]
The next days we publish the version 0.4 with Spark 1.6 and 1.5 compatible and then the version 0.5 with Spark 2.0.x compatible.

Thanks @eranmiz132

**Comment by armaseg** [comment]
Hello,

I'm trying to use your new artifacts -> version 0.5. But I can't find the file **spark-rabbitmq-0.5.0.jar**. 

![maven-05](https://cloud.githubusercontent.com/assets/1028859/21320563/cc0b63e6-c611-11e6-88a9-a2849584a425.PNG)

Regards,
