### ISSUE TITLE
Difference of AckType :basic and auto

### ISSUE THREAD

**Issue by louishigher** [Stratio/spark-rabbitmq#67]
What's the difference of AckType: basic and auto?

**Comment by nelsou** [comment]
auto means the ack is done automatically after the get
basic means you have to ack yourself after the get

**Comment by louishigher** [comment]
Thank you for the reply！

**Comment by fpousserot** [comment]
hi, 
Have you an example of use for basic mode, such hdfs save in the message and indicate rabbit that the message is read correctly ? 
Merci

**Comment by louishigher** [comment]
Sorry, I did not use this mode. Did you do it sucessfully?@fpousserot

**Comment by fpousserot** [comment]
No, i don't know how use the ack basic mode :(

**Comment by compae** [comment]
If you use auto the ack is controlled by the library, but if you use basic, the ack is controlled inside the receiver.

This ack approach have one bug and is solved in the pr #83

**Comment by compae** [comment]
The PR have been merged now.

Thanks!!
