### ISSUE TITLE
Basic ackType problems -- queue

### ISSUE THREAD

**Issue by louishigher** [Stratio/spark-rabbitmq#70]
When I set actType to basic , the MQ queue got blocked after a while , but when I set it to auto , the app works well. What 's causing this ?

**Comment by nelsou** [comment]
Hi @louishigher 
Do you have unack messages like #63 ?

**Comment by louishigher** [comment]
Hi @nelsou ,yes , I have same situation as you ! Have you solved it?

**Comment by nelsou** [comment]
No :/
After searching for days, I set the ackType to auto. Acks are done on every get.

**Comment by louishigher** [comment]
Can auto ackType ensure zero data losss?

**Comment by fpousserot** [comment]
Hi, have you an example of use the ackType basic mode ?

**Comment by compae** [comment]
This ack approach have one bug and is solved in the pr #83

**Comment by compae** [comment]
The PR have been merged now. 

Thanks!!
