### ISSUE TITLE
build fails for Spark 2.0 due to removal of org.apache.spark.Logging and akka

### ISSUE THREAD

**Issue by palaiyacw** [Stratio/spark-rabbitmq#72]
We were planning to shift to Spark 2.0 along with their dependencies. So, currently we are using this Connector. Which internally imports `org.apache.spark.Logging` . But in the Spark 2.0 it has been made private. Morover, the support for streaming connectors like Akka also have been removed So, what could be the work around to build it for Spark 2.0

**Comment by tipok** [comment]
I've created a fork for spark 2.0. It's still dependent on Akka but the newest version, so you'll have to bring Akka as dependency to your Spark job.
I haven't created a pull request because the changes aren't compatible to Spark prior 2.0
https://github.com/tipok/Spark-RabbitMQ

**Comment by brijeshkec11** [comment]
can we have beta version published to maven repo? I also want to give a try with spark 2.0.

**Comment by compae** [comment]
The next weeks we publish one version compatible with Spark 2.0. Thanks for all.

**Comment by sornalingam** [comment]
@compae , Can you please let me know is there any update on this ?

**Comment by brijeshkec11** [comment]
@compare, any success so far?

**Comment by cw-deenbandhu** [comment]
@compae Any update ?

**Comment by compae** [comment]
The PR #90 support Spark 2.0 in the version 0.5 will be available.

Thanks for all.

**Comment by compae** [comment]
Can I close this issue @palaiyacw @tipok @brijeshkec11 @sornalingam @cw-deenbandhu ????

**Comment by compae** [comment]
Duplicated

**Comment by palaiyacw** [comment]
@compare ThankingYou :+1:

**Comment by palaiyacw** [comment]
@compae Why still in the current release you have used `import org.apache.spark.internal.Logging`. Whereas in the Spark Official documentation it is not recommended to use internal logging mechanism of spark
