### ISSUE TITLE
Problem receiving an Array(Byte) using Scala API

### ISSUE THREAD

**Issue by pedroszattoni** [Stratio/spark-rabbitmq#74]
Using this line of code the receiver works fine:
`val receiverStream = RabbitMQUtils.createStream[String](ssc, rabbitParams)`

But when I try to receive a Array(Byte) with the following code:
`val receiverStream = RabbitMQUtils.createStream(ssc, rabbitParams)`
I get the following message:
`ambiguous reference to overloaded definition, both method createStream in object RabbitMQUtils of type [R >: String <: String](ssc: org.apache.spark.streaming.StreamingContext, params: Map[String,String])(implicit evidence$2: Manifest[R])org.apache.spark.streaming.dstream.ReceiverInputDStream[String] and method createStream in object RabbitMQUtils of type (ssc: org.apache.spark.streaming.StreamingContext, params: Map[String,String])org.apache.spark.streaming.dstream.ReceiverInputDStream[Array[Byte]] match argument types (org.apache.spark.streaming.StreamingContext,scala.collection.immutable.Map[String,String])`

**Comment by compae** [comment]
Hi @pedroszattoni 

thanks for the report, this issue have been solved in the PR #86
