### ISSUE TITLE
Problem trying to configure 'x-message-ttl'

### ISSUE THREAD

**Issue by pedroszattoni** [Stratio/spark-rabbitmq#75]
I am currently trying to configure the "x-message-ttl" param in my receiver, but I am getting the following error: 

`Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'xxxxx' in vhost '/': received '10000' but current is '10000', class-id=50, method-id=10)`.

The rabbitParams I'm using are:

```
val rabbitParams =  Map(
      "hosts" -> "xxxxx",
      "queueName" -> "xxxxx",
      "exchangeName" -> "xxxxx",
      "userName" -> "xxxxx",
      "password" -> "xxxxx",
      "storageLevel" -> "MEMORY_AND_DISK_SER_2",
      "durable" -> "false",
      "x-message-ttl" -> "10000"
    )
```

Can anyone help me?

**Comment by croofec** [comment]
i fixed here https://github.com/Stratio/Spark-RabbitMQ/pull/73

**Comment by alankala** [comment]
I'm hitting the same issue with x-max-length. Is this fix in the master branch yet? If yes, what would be the maven version.
Thanks.

**Comment by compae** [comment]
The PR #73 have been merged now. Thanks for all @croofec
