### ISSUE TITLE
Is there a way to retrieve the Routing key along with the message from Rabbit?

### ISSUE THREAD

**Issue by myali05** [Stratio/spark-rabbitmq#85]
Hi,

I have a situation where I need to read off a rabbit queue where the routing key contains a wildcard indicating a device id ... i.e. "gps.#" . # represents an alphanumeric id. The message itself does not contain this device id. When I read the RDD I don't see a way to extract the routing key. Is there a way to extract the routing key for each message?

**Comment by pedroszattoni** [comment]
Check the issue [#55](https://github.com/Stratio/spark-rabbitmq/issues/51) and pull request [#71](https://github.com/Stratio/spark-rabbitmq/pull/77) .

**Comment by compae** [comment]
The PR #71 have been merged now. Thanks for the report @myali05 and the response @pedroszattoni
