### ISSUE TITLE
No spark-rabbitmq-0.5.0.jar on Maven

### ISSUE THREAD

**Issue by armaseg** [Stratio/spark-rabbitmq#95]
Hello,

I'm trying to use your new artifacts -> version 0.5. But I can't find the file spark-rabbitmq-0.5.0.jar.

![maven-05](https://cloud.githubusercontent.com/assets/1028859/21423285/8a471694-c83c-11e6-852e-5daa80b9f179.PNG)

Regards,

**Comment by armaseg** [comment]
Jar file is again available on [0.5.1](http://repo1.maven.org/maven2/com/stratio/receiver/spark-rabbitmq/0.5.1/)

**Comment by mrgordon** [comment]
Looks like this can be closed
